// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// CreateOrGet provides a mock function for the type MockURLService
func (_mock *MockURLService) CreateOrGet(ctx context.Context, longURL string) (string, error) {
	ret := _mock.Called(ctx, longURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGet")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, longURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, longURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, longURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLService_CreateOrGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGet'
type MockURLService_CreateOrGet_Call struct {
	*mock.Call
}

// CreateOrGet is a helper method to define mock.On call
//   - ctx context.Context
//   - longURL string
func (_e *MockURLService_Expecter) CreateOrGet(ctx interface{}, longURL interface{}) *MockURLService_CreateOrGet_Call {
	return &MockURLService_CreateOrGet_Call{Call: _e.mock.On("CreateOrGet", ctx, longURL)}
}

func (_c *MockURLService_CreateOrGet_Call) Run(run func(ctx context.Context, longURL string)) *MockURLService_CreateOrGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLService_CreateOrGet_Call) Return(s string, err error) *MockURLService_CreateOrGet_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLService_CreateOrGet_Call) RunAndReturn(run func(ctx context.Context, longURL string) (string, error)) *MockURLService_CreateOrGet_Call {
	_c.Call.Return(run)
	return _c
}

// GetLongURLByAlias provides a mock function for the type MockURLService
func (_mock *MockURLService) GetLongURLByAlias(ctx context.Context, alias string) (string, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetLongURLByAlias")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLService_GetLongURLByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLongURLByAlias'
type MockURLService_GetLongURLByAlias_Call struct {
	*mock.Call
}

// GetLongURLByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLService_Expecter) GetLongURLByAlias(ctx interface{}, alias interface{}) *MockURLService_GetLongURLByAlias_Call {
	return &MockURLService_GetLongURLByAlias_Call{Call: _e.mock.On("GetLongURLByAlias", ctx, alias)}
}

func (_c *MockURLService_GetLongURLByAlias_Call) Run(run func(ctx context.Context, alias string)) *MockURLService_GetLongURLByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLService_GetLongURLByAlias_Call) Return(s string, err error) *MockURLService_GetLongURLByAlias_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLService_GetLongURLByAlias_Call) RunAndReturn(run func(ctx context.Context, alias string) (string, error)) *MockURLService_GetLongURLByAlias_Call {
	_c.Call.Return(run)
	return _c
}
