// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Rasulikus/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// CreateOrGet provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) CreateOrGet(ctx context.Context, u *model.URL) (*model.URL, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGet")
	}

	var r0 *model.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.URL) (*model.URL, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.URL) *model.URL); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.URL) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_CreateOrGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGet'
type MockURLRepository_CreateOrGet_Call struct {
	*mock.Call
}

// CreateOrGet is a helper method to define mock.On call
//   - ctx context.Context
//   - u *model.URL
func (_e *MockURLRepository_Expecter) CreateOrGet(ctx interface{}, u interface{}) *MockURLRepository_CreateOrGet_Call {
	return &MockURLRepository_CreateOrGet_Call{Call: _e.mock.On("CreateOrGet", ctx, u)}
}

func (_c *MockURLRepository_CreateOrGet_Call) Run(run func(ctx context.Context, u *model.URL)) *MockURLRepository_CreateOrGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.URL
		if args[1] != nil {
			arg1 = args[1].(*model.URL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_CreateOrGet_Call) Return(uRL *model.URL, err error) *MockURLRepository_CreateOrGet_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *MockURLRepository_CreateOrGet_Call) RunAndReturn(run func(ctx context.Context, u *model.URL) (*model.URL, error)) *MockURLRepository_CreateOrGet_Call {
	_c.Call.Return(run)
	return _c
}

// GetLongURLByAlias provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) GetLongURLByAlias(ctx context.Context, alias string) (string, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetLongURLByAlias")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_GetLongURLByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLongURLByAlias'
type MockURLRepository_GetLongURLByAlias_Call struct {
	*mock.Call
}

// GetLongURLByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLRepository_Expecter) GetLongURLByAlias(ctx interface{}, alias interface{}) *MockURLRepository_GetLongURLByAlias_Call {
	return &MockURLRepository_GetLongURLByAlias_Call{Call: _e.mock.On("GetLongURLByAlias", ctx, alias)}
}

func (_c *MockURLRepository_GetLongURLByAlias_Call) Run(run func(ctx context.Context, alias string)) *MockURLRepository_GetLongURLByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_GetLongURLByAlias_Call) Return(s string, err error) *MockURLRepository_GetLongURLByAlias_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLRepository_GetLongURLByAlias_Call) RunAndReturn(run func(ctx context.Context, alias string) (string, error)) *MockURLRepository_GetLongURLByAlias_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) GetLastID(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastID")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastID'
type MockURLRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockURLRepository_Expecter) GetNextID(ctx interface{}) *MockURLRepository_GetNextID_Call {
	return &MockURLRepository_GetNextID_Call{Call: _e.mock.On("GetLastID", ctx)}
}

func (_c *MockURLRepository_GetNextID_Call) Run(run func(ctx context.Context)) *MockURLRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLRepository_GetNextID_Call) Return(v uint64, err error) *MockURLRepository_GetNextID_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockURLRepository_GetNextID_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *MockURLRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}
